#!/bin/bash
# heartbeat-sync.sh — Infer agent heartbeats from session file mtime
# Runs via cron every 5 minutes.
# Writes HEARTBEAT.md for each agent based on actual activity.
#
# Phase 1.8 — fixes the "all 6 heartbeats stale 6-14 days" gap.
# Agent doesn't need to know this exists — cron handles it autonomously.

set -uo pipefail

WORKSPACE="/root/.openclaw/workspace/agents"
NOW_ISO=$(date -Iseconds)
NOW_EPOCH=$(date +%s)
LOG="/var/log/heartbeat-sync.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG"; }

for AGENT in nox atlas boris cipher forge lex; do
  AGENT_DIR="${WORKSPACE}/${AGENT}"
  [ -d "$AGENT_DIR" ] || continue

  SESSIONS_DIR="${AGENT_DIR}/sessions"
  HEARTBEAT_FILE="${AGENT_DIR}/HEARTBEAT.md"

  # Find most-recently-modified session file
  LAST_SESSION=$(find "$SESSIONS_DIR" -maxdepth 1 -type f -name '*.jsonl' -printf '%T@ %f\n' 2>/dev/null | sort -rn | head -1)

  if [ -z "$LAST_SESSION" ]; then
    LAST_AGE_MIN="∞"
    LAST_SEEN_ISO="never"
    STATUS="dormant"
  else
    LAST_MTIME=$(echo "$LAST_SESSION" | awk '{printf "%.0f", $1}')
    LAST_FILE=$(echo "$LAST_SESSION" | cut -d' ' -f2)
    LAST_AGE_MIN=$(( (NOW_EPOCH - LAST_MTIME) / 60 ))
    LAST_SEEN_ISO=$(date -d "@${LAST_MTIME}" -Iseconds 2>/dev/null || echo "unknown")

    if [ "$LAST_AGE_MIN" -lt 30 ]; then
      STATUS="active"
    elif [ "$LAST_AGE_MIN" -lt 1440 ]; then
      STATUS="idle"
    elif [ "$LAST_AGE_MIN" -lt 10080 ]; then
      STATUS="quiet"
    else
      STATUS="dormant"
    fi
  fi

  # Count pending inbox items (for Fase 1.8b inbox infra; defaults to 0 today)
  INBOX_FILE="/root/.openclaw/workspace/shared/agents/${AGENT}/inbox.jsonl"
  PENDING=0
  if [ -f "$INBOX_FILE" ]; then
    PENDING=$(grep -c '"status":"pending"' "$INBOX_FILE" 2>/dev/null || echo 0)
  fi

  # Write HEARTBEAT.md (atomic via tmp + mv)
  TMP="${HEARTBEAT_FILE}.tmp"
  {
    echo "# ${AGENT} heartbeat"
    echo
    echo "- status: ${STATUS}"
    echo "- last_seen: ${LAST_SEEN_ISO}"
    echo "- last_age_min: ${LAST_AGE_MIN}"
    echo "- pending_inbox: ${PENDING}"
    echo "- updated_at: ${NOW_ISO}"
    echo
    echo "_Generated by heartbeat-sync.sh — do not edit manually. Infers activity from session file mtime._"
  } > "$TMP"
  mv "$TMP" "$HEARTBEAT_FILE"
done

log "sync complete"
exit 0
