/**
 * Ground truth for the Paper-2 serving model, generated by DRIVING THE REAL
 * PRODUCTION CODE (dist/api/brief.js + dist/salience.js) against a throwaway
 * SQLite file in /tmp. Never touches the production database.
 *
 * WHY: both reach analyses in the registration were derived from
 * `link_feasibility.mjs` / `reachable_share.py`, which RECONSTRUCT the serving
 * path. Reading the code on 2026-08-18 showed the reconstruction models a
 * threshold that production does not apply. This file makes the code the
 * authority and emits a fixture the paper's scripts must reproduce.
 *
 * SCOPE: this covers the arm-independent baseline (no boost). The outcome boost
 * `W_OUTCOME = w * Delta_cut` DOES NOT EXIST IN THE CODE YET, so nothing here
 * can be ground truth about it. What it can do is pin every OTHER term exactly,
 * so the boost analysis stops resting on a reconstructed baseline.
 */
import Database from "/root/.openclaw/workspace/tools/nox-mem/node_modules/better-sqlite3/lib/index.js";
import { readFileSync, rmSync, existsSync } from "node:fs";
import { buildBriefDiverse, ensureBriefLog } from "/root/.openclaw/workspace/tools/nox-mem/dist/api/brief.js";
import { calculateSalience } from "/root/.openclaw/workspace/tools/nox-mem/dist/salience.js";

const DBP = "/tmp/p2-fixture.db";
for (const s of ["", "-wal", "-shm"]) if (existsSync(DBP + s)) rmSync(DBP + s);
const db = new Database(DBP);
db.exec(`CREATE TABLE chunks (
  id INTEGER PRIMARY KEY AUTOINCREMENT, source_file TEXT NOT NULL,
  chunk_text TEXT NOT NULL, chunk_type TEXT NOT NULL, source_date TEXT,
  is_consolidated INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')), metadata TEXT, memory_type TEXT,
  tier TEXT DEFAULT 'peripheral', access_count INTEGER DEFAULT 0,
  last_accessed_at TEXT, importance REAL DEFAULT 0.5, source_type TEXT,
  is_compiled INTEGER DEFAULT 0, retention_days INTEGER, pain REAL DEFAULT 0.2,
  section TEXT, section_boost REAL DEFAULT 1.0, fts_anchor TEXT DEFAULT '');`);
ensureBriefLog(db);

const NOW = Date.parse("2026-08-18T12:00:00Z");
const iso = (d) => new Date(NOW - d * 86400000).toISOString().slice(0, 19).replace("T", " ");
const SEV = { S1: 0.25, S2: 0.50, S3: 0.75, S4: 1.00 };
const SHARE = { S1: 0.6973, S2: 0.2962, S3: 0.0058, S4: 0.0008 };
const EPISODES = 396;

const ins = db.prepare(
  `INSERT INTO chunks (source_file, chunk_text, chunk_type, source_date, created_at,
     updated_at, importance, pain, access_count, last_accessed_at, retention_days)
   VALUES (?,?,?,?,?,?,?,?,?,?,?)`);

/** competitor set = one epoch of the study's own inflow, all never-served */
function seedStudyInflow() {
  let n = 0;
  for (const [k, sev] of Object.entries(SEV)) {
    const qty = Math.round(EPISODES * SHARE[k]);
    for (let i = 0; i < qty; i++) {
      ins.run(`memory/entities/lessons/inflow-${k}-${i}.md`, `competitor ${k} ${i}`,
              "lesson", iso(0.2), iso(0.2), iso(0.2), 0.90, sev, 0, null, 180);
      n++;
    }
  }
  return n;
}

/** a plausible main-pool background so CUT_MAIN is not degenerate */
function seedMainBackground(qty = 800) {
  for (let i = 0; i < qty; i++) {
    const t = ["decision", "lesson", "project", "daily", "feedback"][i % 5];
    ins.run(`memory/mac-docs/bg/${i}.md`, `bg ${i}`, t, iso(5 + (i % 400)),
            iso(5 + (i % 400)), iso(5 + (i % 400)), null, 0.2, i % 3, null, null);
  }
}

const PARAMS = { scope: "global", agent: null, n: 10 };
const CFG = { freshSlots: 2, freshMinImp: 0.7, freshMinPain: 0.7,
              freshMaxAgeDays: 7, freshGlobalMaxAgeDays: 30,
              noveltyPMax: 0, noveltyHalfLife: 1 };

function probe(sev, ageDays) {
  const id = ins.run(`memory/entities/lessons/CANDIDATE.md`, "candidate chunk",
    "lesson", iso(ageDays), iso(ageDays), iso(ageDays), 0.90, sev, 0, null, 180).lastInsertRowid;
  const row = db.prepare("SELECT * FROM chunks WHERE id=?").get(id);
  const sal = calculateSalience(row, NOW);
  let out;
  try {
    const r = buildBriefDiverse(db, PARAMS, CFG, NOW);
    const cur = r.current.items.map((x) => x.id ?? x.chunk_id);
    const alt = r.alt.items.map((x) => x.id ?? x.chunk_id);
    out = { no_baseline: cur.includes(Number(id)),
            no_servido: alt.includes(Number(id)),
            fresh_added: r.diff.fresh_added,
            rank_no_servido: alt.indexOf(Number(id)),
            n_baseline: cur.length, n_servido: alt.length };
  } catch (e) { out = { erro: String(e).slice(0, 160) }; }
  db.prepare("DELETE FROM chunks WHERE id=?").run(id);
  return { salience: sal, ...out };
}

const fixture = { gerado_em: new Date(NOW).toISOString(), now_ms: NOW,
  fonte: "dist/api/brief.js + dist/salience.js na VPS, 2026-08-18",
  cfg: CFG, params: PARAMS, cenarios: {} };

seedMainBackground();
for (const cenario of ["pool_vazio", "pool_do_estudo"]) {
  if (cenario === "pool_do_estudo") fixture.inflow_semeado = seedStudyInflow();
  const res = {};
  for (const [k, sev] of Object.entries(SEV))
    for (const age of [0, 1, 3, 7, 14, 29, 31])
      res[`${k}@${age}d`] = probe(sev, age);
  fixture.cenarios[cenario] = res;
}
console.log(JSON.stringify(fixture, null, 1));
