#!/usr/bin/env python3
"""Parity check B-v2-rc10.md -> B-v2-rc11.md (Paper B, sprint 2026-10-04; rc11 2026-10-05).

rc11 applies the review of rc10 (`REVIEW-B-rc10-2026-10-05.md`: Fable HIGH-1, MEDIUM-1/2,
LOW-3..6; Codex 1..9), each finding verified first (`APPLY-B-rc11.md`). No analysis changes:
`out/ITT-REGISTRADO-v3-2026-10-05.json` was regenerated by the comment-corrected script and is
identical to rc10's in every field except `gerado_em` and the script sha256.

The diff is cut into hunks (difflib on lines). Every hunk must carry at least one ID, assigned
by an anchor substring of the rc11 hunk (ANCHORS):
    ST status header and review caveat · CENSUS the sample that replaced the registered census
    (Codex 1) · DOSE what the switch-6 correction shows and does not (Codex 2, Fable MEDIUM-1)
    · STRAT the own stratum and the session before the window (Codex 3, Fable LOW-4) · SPAN
    the one-minute floor of `span_por_sessao` (Codex 4) · STALE status sentences older than
    rc10 (Fable HIGH-1, Codex 5, 6, 9) · COST what H2 measures (Codex 7) · MANI the ballast
    manifest's coverage (Codex 8) · H2PCT H2's percentile intervals (Fable MEDIUM-2) · EXPIRY
    the expiry cut under start-epoch attribution (Fable LOW-5) · TIES ties under rc10 in §7
    (Fable LOW-6) · SCRIPT the corrected script, its sha256 and the frozen copies (Fable LOW-3)
    · APPB / B1 appendices · CL working list and changelog.

Checks (exit 1 if any fails):
  1. hunks: every hunk has an ID.
  2. numbers: every numeric token ADDED in a hunk is (a) already in rc10, or (b) a leaf of an
     artifact read at run time, in one of the paper's roundings, or (c) DERIVED at run time
     from an artifact or source (the stratum contrasts, 4 756 = 5 556 − 800, the latest epoch
     a crossing session touches, the 3600 of `span_por_sessao`, the date of the PREREG §3
     lock), or (d) listed in LITERALS for one of the hunk's IDs with its source.
     --report prints, per ID, every added and removed number and the class that justifies it.
  3. headline values: strings formatted from the artifacts at run time must be present (the
     rc10 headlines, kept, and the rc11 ones: stratum contrasts, H2 percentile intervals, the
     census numbers, the span floor, the script sha256 prefix).
  4. claims, outside struck text and before the working list:
     (a) no sentence presents H1a as rejected;
     (b) LOCK kept from rc9: no sentence presents H1 as rejecting without "deposited";
     (c) LOCK kept from rc10: no sentence presents H1 as rejecting in "the registered analysis"
         unless it places the rejection in the sensitivity analysis or an earlier version;
     (d) stopping condition "was met" only with "planning"; §4.6 never calls its correlation
         "M10" without "registered"/"called"/"label"; `1 195` never called adjudicated;
     (e) NEW in rc11: no sentence says the switch-6 change shows "not the dose" / "no effect of
         the dose" (Codex 2): the patterns in DOSE_LOCK are forbidden; "not that the dose had no
         effect" is the allowed negation;
     (f) NEW in rc11: none of the stale sentences the review found (STALE) is present.
  5. headings identical (rc11 renames none).
  6. citations unchanged and listed; footnotes defined; DOIs unchanged.
  7. no host, IP or personal path added.
  8. SHAM-JANELA: exactly 10 blocks, byte-identical to rc10's.
  9. no REANALISE marker.
 10. quotes: every *"..."* span added occurs verbatim (bold and whitespace normalized) in rc10
     or in a declared source document.
 11. code spans: every added span that names a file resolves on disk; added snake_case
     identifiers occur in the artifacts or sources they name.
 12. bold balance: every paragraph has an even number of `**`.
 13. script (Fable LOW-3): the running estimator, its frozen copy and the v3 provenance share
     one sha256; the regenerated v3 equals the kept rc10 v3 in every field except `gerado_em`
     and `proveniencia.script.sha256`; the kept rc10 bytes hash to what `checks-rc10.json` and
     the rc10 figure pin; the stale strings are gone from the script.

Usage:  python3 parity-rc11.py              # check
        python3 parity-rc11.py --report     # per-ID numeric deltas with their justification
        python3 parity-rc11.py --self-test  # mutations in memory; each must fail a content check
Reads the two manuscripts and the artifacts named below. Writes nothing.
"""
import collections
import copy
import difflib
import glob
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SPRINT = HERE.parent
P2 = SPRINT.parent
REPO = P2.parent
LASTRO = Path.home() / "Backups" / "paper2-ensaio-2026-09-21"
OLD = SPRINT / "B-v2-rc10.md"
NEW = SPRINT / "B-v2-rc11.md"
REG = SPRINT / "B-registered"
SCRIPT = P2 / "measurement" / "estimador_itt_registrado.py"
KEPT_V3 = REG / "ITT-REGISTRADO-v3-rc10-36f6421a.json"
KEPT_SCRIPT = REG / "estimador_itt_registrado-v3-rc10-b5135f04.py"
ART = {
    "ITT-REGISTRADO-v3": P2 / "out" / "ITT-REGISTRADO-v3-2026-10-05.json",
    "checks-rc10": SPRINT / "B-rc10" / "checks-rc10.json",
    "ITT-2026-09-21": LASTRO / "ITT-2026-09-21.json",
    "figB1-v3": SPRINT / "figures" / "figB1-h1a-inversao-registrado-v3.run.json",
    "ITT-REGISTRADO-v2": P2 / "out" / "ITT-REGISTRADO-v2-2026-10-05.json",
    "f4-w4": REG / "f4-promoviveis-w4.json",
    "f3-abort": REG / "f3-abort-ex-post.json",
}
QUOTE_SOURCES = [P2 / "PROSPECTIVE-ESTIMAND-2026-08-30.md", P2 / "PREREG-DRAFT.md",
                 P2 / "ASSIGN-SEED-2026-08-30.md"]

# ---------------------------------------------------------------- tokenization (as rc10)
SECREF = re.compile(r"§§?\s?(\d+(?:\.\d+)*[a-z]?)(?:\(\d+\))?(?:[–-]§?\d+(?:\.\d+)*[a-z]?)?")
CITE = re.compile(r"\[@[^\]]+\]")
LISTNUM = re.compile(r"^(\s*)\d+\.\s", re.M)
DATE = (r"\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}(?::\d{2})?Z?)?"
        r"|\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?Z?"
        r"|(?<![\d-])\d{2}-\d{2}(?![\d-])")
TOK = re.compile(r"(?<![A-Za-z_\d.,])(" + DATE + r"|\d+(?:[.,]\d+)*)(?![A-Za-z_\d]|\.\d)")
HEADNUM = re.compile(r"^(#{1,6} )(?:Appendix )?[A-Z]?\.?\d+(?:\.\d+)*[a-z]?", re.M)
SECCELL = re.compile(r"\|\s*(?:Abstract, )?\d+(?:\.\d+)*[a-z]?(?:\s*[,–]\s*\d+(?:\.\d+)*[a-z]?)*\s*(?=\|)")
CODE = re.compile(r"`([^`\n]+)`")
QUOTE = re.compile(r"(?<!\*)\*\".*?\"\*(?!\*)", re.S)
DOI = re.compile(r"10\.\d{4,9}/[^\s`)]+")
S_OPEN, S_CLOSE = "<!-- SHAM-JANELA: pending -->", "<!-- /SHAM-JANELA -->"
R_ANY = re.compile(r"<!-- (?:REANALISE(?:: rewrite)?|/REANALISE) -->")
EXPECTED_SHAM = 10


def normalize(text):
    text = CITE.sub(" ", text)
    text = HEADNUM.sub(r"\1", text)
    text = SECCELL.sub("| ", text)
    text = SECREF.sub(" ", text)
    text = LISTNUM.sub(r"\1", text)
    prev = None
    while prev != text:
        prev = text
        text = re.sub(r"(?<![\d.,])(\d{1,3}) (\d{3})(?![\d,])", r"\1\2", text)
    return text


def numbers(text):
    return collections.Counter(TOK.findall(normalize(text)))


# ---------------------------------------------------------------- hunk IDs
ANCHORS = [
    ("ST", "rc11 prepared"),
    ("ST", "has been under review since 2026-09-21"),
    ("H2PCT", "registered BCa construction, by margins the percentile construction does not hold"),
    ("DOSE", "result did not survive the registered attribution of three long sessions"),
    ("STALE", "contemporaneous execution record for the safety abort is declared in Appendix A"),
    ("EXPIRY", "The cut is applied to episodes attributed to `09-20`"),
    ("STRAT", "taking the episodes it had in `09-02`…`09-07` with it"),
    ("STRAT", "Within this stratum, the descriptive treatment–control"),
    ("CENSUS", "**Deviation (rc11): a sample where the registration"),
    ("DOSE", "The earlier rejection disappears when sessions are attributed"),
    ("DOSE", "was computed with a few long sessions cut"),
    ("SPAN", "computes `max((max(ts) − min(ts))/3600, 1/60)` hours"),
    ("SPAN", "first and last event with a one-minute minimum"),
    ("STALE", "PREREG §5 requires an ITT co-estimate over all post-washout"),
    ("STALE", "the registered re-analysis resolved (the six switches of §4)"),
    ("H2PCT", "Both exclude zero under the registered BCa construction only"),
    ("TIES", "under the rc10 analysis 4 fall in the analysed exposure of"),
    ("STALE", "from rc10 every session is counted in the epoch"),
    ("COST", "We report action-level time and token regret (§5), but no per-phase"),
    ("COST", "or attribute resources to memory phases"),
    ("DOSE", "that rejection went with the denominator: it disappears once sessions"),
    ("DOSE", "artifact of an unregistered denominator, and the registered non-rejection"),
    ("DOSE", "was computed with long, mostly idle sessions split across the epochs"),
    ("STALE", "the safety abort without an execution record, the registered M10"),
    ("DOSE", "registration's own attribution rule removed it."),
    ("CENSUS", "declared here and in §1, §2, §3.0, §4, §4.6 and §5"),
    ("CENSUS", "~~Twelve~~ Thirteen that a reader"),
    ("STALE", "Under the deposited reading, H1 rejects in the earlier sensitivity"),
    ("CENSUS", "- PREREG §3 required census adjudication of the live study."),
    ("SCRIPT", "Script sha256 `0aa9202b…` from rc11"),
    ("MANI", "SHA-256 hashes of the 50 artifacts currently covered"),
    ("B1", "*(rc11)* H2's percentile intervals"),
    ("B1", "*(rc11)* the latest epoch a boundary-crossing session touches"),
    ("B1", "| adjudication sample, declared as a deviation from the registered census (rc11)"),
    ("APPB", "The artifacts added in rc7, rc8, rc9, rc10 and rc11"),
    ("APPB", "Figure B1, and the three copies frozen in rc11"),
    ("CL", "*(rc11)* also the frozen v3 script"),
    ("CL", "23. ~~**Review of rc10**"),
    ("CL", "→ **Done, 2026-10-05**: two full"),
    ("CL", "**rc11: review of rc10 applied**"),
]

# (d) literals: numbers added that are neither in rc10 nor in an artifact nor derived
LITERALS = {
    "ST": {"2026-10-05": "date of rc11"},
}

HEADINGS = {}
FORBIDDEN = [r"\b\d{1,3}(?:\.\d{1,3}){3}\b", r"/Users/", r"~/", r"/var/", r"/root/", r"/tmp/",
             r"\$NOX_", r"srv\d+", r"\.hostinger", r"@[a-z0-9-]+\.(?:com|br|ai)\b"]

# 4(e): what the switch-6 correction may NOT be said to show
DOSE_LOCK = [
    r"\bnot (?:a property )?of the dose\b",
    r"\band not the dose\b",
    r"\b(?:was|were|is) (?:the denominator )?(?:and )?not the dose\b",
    r"\bno effect of the dose\b",
    r"(?<!not that )\bthe dose had no effect\b",
    r"\brather than (?:of )?the dose\b",
    r"\binstead of the dose\b",
]
# 4(f): stale sentences found by the review of rc10 (whitespace-normalized, outside struck text)
STALE = [
    "sessions that span more than one epoch are not attributed as the registration requires",
    "no registered verdict differs between them",
    "without coverage exclusion is the primary and is what",
    "report no cost, latency or energy",
    "estimate carryover or measure cost",
    "sha256 of every artifact in this table, for loss detection",
    "The unexecuted abort is declared in Appendix A",
    "no contrast is estimable inside it",
    "computes `max(ts) − min(ts)` over a session's episodes",
    "leaves the analysis with its 49 episodes",
    "outside the four departures the registered re-analysis resolved",
    "is under review as of 2026-09-21",
]
SCRIPT_STALE = ["adds\nfour switches", "all four switches at the CURRENT", "THE FOUR SWITCHES",
                "is not\n    implemented"]


# ---------------------------------------------------------------- artifact-derived numbers
def leaves(o):
    if isinstance(o, dict):
        for v in o.values():
            yield from leaves(v)
    elif isinstance(o, list):
        for v in o:
            yield from leaves(v)
    elif isinstance(o, (int, float)) and not isinstance(o, bool):
        yield float(o)


def forms(v):
    out = set()
    for x in (abs(v), abs(v) * 100):
        for d in range(0, 6):
            t = f"{x:.{d}f}"
            out.add(t)
            if "." in t:
                out.add(t.rstrip("0").rstrip(".") if d else t)
        if float(x).is_integer():
            out.add(str(int(x)))
    return out


def artifact_numbers():
    allowed = {}
    for name, p in ART.items():
        for v in leaves(json.loads(p.read_text())):
            for f in forms(v):
                allowed.setdefault(f, name)
    return allowed


def stratum(reg):
    """Own stratum = registered leg minus the registered 'without' leg, per arm (v3)."""
    a = reg["pernas"]["registrado"]["por_braco"]
    b = reg["pernas"]["sens_registrado_sem_sessoes_atravessadas"]["por_braco"]
    s = {arm: {k: round(a[arm][k] - b[arm][k], 6) for k in ("horas_sessao", "oportunidades", "repeats")}
         for arm in a}
    t, c = s["treatment"], s["control"]
    assert c["oportunidades"] == 0 and c["repeats"] == 0, "control stratum is no longer empty"
    return dict(s=s, rep_h=t["repeats"] / t["horas_sessao"] - c["repeats"] / c["horas_sessao"],
                opp_h=t["oportunidades"] / t["horas_sessao"] - c["oportunidades"] / c["horas_sessao"])


def derived(reg, chk, itt):
    out = {}
    st = stratum(reg)
    out[f"{st['rep_h']:.5f}"] = "stratum: Δ repeats/hour = registered − 'without' leg, per arm (v3)"
    out[f"{st['opp_h']:.5f}"] = "stratum: Δ opportunities/hour = registered − 'without' leg, per arm (v3)"
    out[str(itt["n_resto_no_corpus"] - itt["n_estrato_b_amostrado"])] = \
        "stratum-B episodes outside the sample = n_resto_no_corpus − n_estrato_b_amostrado (ITT-2026-09-21)"
    ult = max(e for s in chk["S_sessoes_atravessadas"]["sessoes"].values() for e in s["epochs_tocados"])
    out[ult[5:]] = "latest epoch touched by a boundary-crossing session (checks-rc10 block S)"
    pr = (P2 / "pilot_replay.py").read_text()
    assert "total_seconds() / 3600, PISO_SESSAO_H" in pr and "PISO_SESSAO_H = 1 / 60" in pr
    out["3600"] = "seconds per hour in span_por_sessao (pilot_replay.py)"
    m = re.search(r"Live-study adjudication volume and panel — LOCKED (\d{4}-\d{2}-\d{2})",
                  (P2 / "PREREG-DRAFT.md").read_text())
    out[m.group(1)] = "date of the PREREG §3 census lock (PREREG-DRAFT.md)"
    return out


# ---------------------------------------------------------------- helpers
def headings(text):
    return [l.rstrip() for l in text.splitlines() if re.match(r"^#{1,6} ", l)]


def body_and_refs(text):
    i = text.find("\n## References")
    j = text.find("\n## Appendix A")
    return text[:i] + text[j:], text[i:j]


def sham_spans(text):
    spans, errs, pos = [], [], 0
    while True:
        i = text.find(S_OPEN, pos)
        j = text.find(S_CLOSE, pos)
        if i < 0 and j < 0:
            break
        if i < 0 or (0 <= j < i):
            errs.append(f"sham: closing marker without opening at offset {j}")
            break
        k = text.find(S_CLOSE, i)
        n2 = text.find(S_OPEN, i + len(S_OPEN))
        if k < 0:
            errs.append(f"sham: opening marker at offset {i} never closed")
            break
        if 0 <= n2 < k:
            errs.append(f"sham: nested opening marker at offset {n2}")
            break
        spans.append(text[i + len(S_OPEN):k])
        pos = k + len(S_CLOSE)
    return spans, errs


def hunks(old, new):
    a, b = old.splitlines(), new.splitlines()
    sm = difflib.SequenceMatcher(None, a, b, autojunk=False)
    out = []
    for t, i1, i2, j1, j2 in sm.get_opcodes():
        if t == "equal":
            continue
        texto = "\n".join(b[j1:j2])
        ids = []
        for aid, anc in ANCHORS:
            if anc in texto and aid not in ids:
                ids.append(aid)
        out.append(dict(rc10=(i1 + 1, i2), rc11=(j1 + 1, j2), ids=ids, old="\n".join(a[i1:i2]), new=texto))
    return out


def strip_struck(text):
    return re.sub(r"~~.*?~~", " ", text, flags=re.S)


def fmt2(x, sinal=False):
    t = f"{x:+.2f}" if sinal else f"{x:.2f}"
    return t.replace("-", "−")


def fmt4(x):
    return f"{x:+.4f}".replace("-", "−") if x else "0"


def fmt_int(x, sinal=True):
    s = f"{abs(round(x)):,}".replace(",", " ")
    return (("+" if x >= 0 else "−") if sinal else "") + s


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def headline(reg, chk, f4, f3, itt):
    """rc10's headline strings (kept) plus rc11's, all formatted from the artifacts."""
    r = reg["pernas"]["registrado"]["hipoteses"]
    lo, hi = r["H1c"]["ic95"]
    d = reg["pernas"]["sens_registrado_sem_sessoes_atravessadas"]["hipoteses"]
    e4 = f4["epoch_1"]["4"]["epoch_1_inteiro"]
    ss = chk["S_sessoes_atravessadas"]["sessoes"]
    ci = lambda x: f"[{fmt2(x[0], True)}; {fmt2(x[1], True)}]"  # noqa: E731
    st = stratum(reg)
    h2 = reg["H2"]["registrado"]
    tp = h2["tempo_s"]["estimador_winsorizado"]["ic95_percentil"]
    kp = h2["tokens"]["estimador_bruto"]["ic95_percentil"]
    tf = lambda x: f"{x:+.3f}".replace("-", "−")  # noqa: E731
    n_b, n_rest, w_b = itt["n_estrato_b_amostrado"], itt["n_resto_no_corpus"], itt["peso_estrato_b"]
    assert abs(n_rest / n_b - w_b) < 5e-4, "HT weight is not n_resto / n_amostrado"
    return {
        # kept from rc10
        "H1 p (registered)": f"`p = {r['H1']['p_rerand']}`",
        "H1 point and BCa CI": f"`H1` returns {fmt2(r['H1']['dif_pontual'])}, BCa CI {ci(r['H1']['ic95'])}",
        "H1a point and BCa CI": f"{fmt2(r['H1a']['dif_pontual'])} · CI {ci(r['H1a']['ic95'])} · **contains zero**",
        "H1c p": f"`p = {r['H1c']['p_rerand']}`",
        "Holm all 1.0": "every Holm-adjusted p-value in the family is 1.0",
        "H1c CI": f"[{fmt4(lo)}; {fmt4(hi)}]",
        "hours v3": f"{reg['pernas']['registrado']['por_braco']['treatment']['horas_sessao']} / "
                    f"{reg['pernas']['registrado']['por_braco']['control']['horas_sessao']}",
        "washout episodes v3": f"removes {chk['W_washout']['episodios_removidos_pelo_washout']} episodes",
        "without p": f"{d['H1']['p_rerand']}, {d['H1a']['p_rerand']} and {d['H1c']['p_rerand']}",
        "longest session": f"spans {ss['d37a5964']['span_h']:.2f} h with {ss['d37a5964']['episodios']} episodes",
        "w=4 coverage": f"{100 * e4['cobertura']:.1f}% ({e4['cobertas']} of {e4['oportunidades']}",
        "abort adjudicated": f"{f3['substituicao']['total']['adjudicados']} episodes",
        # rc11
        "stratum repeats/hour": f"{st['rep_h']:+.5f} repeated failures/hour",
        "stratum opportunities/hour": f"{st['opp_h']:+.5f} opportunities/hour",
        "stratum H1c": "H1c cannot be contrasted because control has no eligible opportunities",
        "H2 percentile": f"time [{tf(tp[0])}; {tf(tp[1])}], tokens [{fmt_int(kp[0])}; {fmt_int(kp[1])}]",
        "census numbers": f"a census of the `is_error` stratum and a sample of {n_b} of the "
                          f"{fmt_int(n_rest, False)} remaining corpus episodes, weighted by {w_b}",
        "census deviation": "This departs from the deposited sampling plan; the six-switch reanalysis does not restore the census",
        "span floor": "`max((max(ts) − min(ts))/3600, 1/60)` hours",
        "script sha8": f"Script sha256 `{sha(SCRIPT)[:8]}…` from rc11",
        "frozen copy": f"`_sprint-2026-10-04/B-registered/estimador_itt_registrado-v3-{sha(SCRIPT)[:8]}.py`",
        "v3 sha8": f"(`{sha(ART['ITT-REGISTRADO-v3'])[:8]}…`)",
        "manifest coverage": f"SHA-256 hashes of the {json.loads((LASTRO / 'MANIFESTO-LASTRO-P2.json').read_text())['n_artefatos']} artifacts currently covered",
        "dose negation": "not that the dose had no effect",
    }


HYP = re.compile(r"\bH1[abc]?\b|\bH2\b")
REJ = re.compile(r"\b(?:rejects?|rejected|rejection)\b")


def sentences(corpo):
    return re.split(r"(?<=[.])\s+|\s*\|\s*", corpo)


def claims(new):
    fails = []
    corpo = strip_struck(new[:new.find("\n## Working list")])
    for sent in sentences(corpo):
        for m in REJ.finditer(sent):
            antes = list(HYP.finditer(sent[:m.start()]))
            if not antes:
                continue
            sujeito = antes[-1].group(0)
            ini = max(sent.rfind(c, 0, m.start()) for c in ",;:()")
            clause = sent[ini + 1:m.end() + 12]
            negado = bool(re.search(r"\b(?:not|no|nor|never|neither|without|cannot|stops)\b", clause))
            if sujeito == "H1a" and not negado:
                fails.append(f"claim: H1a presented as rejected: {clause.strip()[:90]!r}")
            if sujeito == "H1" and not negado and "deposited" not in sent:
                fails.append(f"claim: H1 presented as rejecting without 'deposited': {sent.strip()[:110]!r}")
            if sujeito == "H1" and not negado and re.search(r"registered\s+analysis", sent) \
                    and not re.search(r"sensitivity|rc8|rc9|earlier", sent):
                fails.append(f"claim: H1 presented as rejecting in the registered analysis: {sent.strip()[:110]!r}")
    for sent in sentences(corpo):
        if re.search(r"\b(?:condition|rule)\b[^.]*\bwas met\b", sent) and "planning" not in sent \
                and "not met" not in sent and "Whether" not in sent:
            fails.append(f"claim: stopping condition 'was met' without the planning qualifier: {sent.strip()[:110]!r}")
    sec46 = corpo[corpo.find("### 4.6"):corpo.find("### 4.7")]
    for sent in sentences(sec46):
        if "M10" in sent and not re.search(r"registered|called|label", sent):
            fails.append(f"claim: §4.6 calls the correlation M10: {sent.strip()[:110]!r}")
    if re.search(r"\b1 195 (?:episodes )?(?:were |are )?adjudicated", corpo):
        fails.append("claim: 1 195 called adjudicated (it is the number submitted)")
    flat = " ".join(corpo.split())
    # (e) the switch-6 correction does not show "not the dose" / "no effect of the dose"
    for pat in DOSE_LOCK:
        for m in re.finditer(pat, flat):
            fails.append(f"claim: switch-6 correction read as about the dose ({pat}): "
                         f"{flat[max(0, m.start() - 80):m.end() + 20]!r}")
    # (f) stale sentences
    for s in STALE:
        if " ".join(s.split()) in flat:
            fails.append(f"claim: stale sentence present: {s!r}")
    return fails


def script_integrity(v3_new, v3_old, script_bytes, frozen_bytes, kept_script_bytes, kept_v3_bytes, chk, fig):
    """Fable LOW-3: same logic, same numbers, hashes recorded where they must be."""
    fails = []
    h_script = hashlib.sha256(script_bytes).hexdigest()
    if hashlib.sha256(frozen_bytes).hexdigest() != h_script:
        fails.append("script: frozen v3 copy differs from measurement/estimador_itt_registrado.py")
    if v3_new["proveniencia"]["script"]["sha256"] != h_script:
        fails.append("script: v3 provenance does not record the running script's sha256")
    a, b = copy.deepcopy(v3_old), copy.deepcopy(v3_new)
    for x in (a, b):
        x.pop("gerado_em", None)
        x["proveniencia"]["script"].pop("sha256", None)
    if a != b:
        fails.append("script: regenerated v3 differs from rc10's v3 outside gerado_em and the script sha256")
    if hashlib.sha256(kept_v3_bytes).hexdigest() != chk["sha256_ITT_REGISTRADO_v3"] or \
            fig["fonte"]["ITT-REGISTRADO"] != chk["sha256_ITT_REGISTRADO_v3"]:
        fails.append("script: kept rc10 v3 bytes do not hash to what checks-rc10 and the rc10 figure pin")
    if hashlib.sha256(kept_script_bytes).hexdigest() != v3_old["proveniencia"]["script"]["sha256"]:
        fails.append("script: kept rc10 script bytes do not hash to rc10's v3 provenance")
    txt = script_bytes.decode()
    for s in SCRIPT_STALE:
        if s in txt:
            fails.append(f"script: stale string still present: {s!r}")
    return fails


def load_integrity_inputs():
    return dict(v3_new=json.loads(ART["ITT-REGISTRADO-v3"].read_text()),
                v3_old=json.loads(KEPT_V3.read_text()),
                script_bytes=SCRIPT.read_bytes(),
                frozen_bytes=(REG / f"estimador_itt_registrado-v3-{sha(SCRIPT)[:8]}.py").read_bytes(),
                kept_script_bytes=KEPT_SCRIPT.read_bytes(), kept_v3_bytes=KEPT_V3.read_bytes(),
                chk=json.loads(ART["checks-rc10"].read_text()),
                fig=json.loads(ART["figB1-v3"].read_text()))


def check(old, new, verbose=True, report=False, integ=None):
    fails = []
    reg = json.loads(ART["ITT-REGISTRADO-v3"].read_text())
    chk = json.loads(ART["checks-rc10"].read_text())
    f4 = json.loads(ART["f4-w4"].read_text())
    f3 = json.loads(ART["f3-abort"].read_text())
    itt = json.loads(ART["ITT-2026-09-21"].read_text())
    allowed_art = artifact_numbers()
    der = derived(reg, chk, itt)
    old_nums = numbers(old)
    hs = hunks(old, new)
    # 1 hunks
    for h in hs:
        if not h["ids"]:
            fails.append(f"hunk rc10 {h['rc10']} rc11 {h['rc11']} has no ID: {h['new'][:70]!r}")
    # 2 numbers per hunk
    rep = collections.defaultdict(lambda: dict(added=[], removed=[]))
    for h in hs:
        add = numbers(h["new"]) - numbers(h["old"])
        rem = numbers(h["old"]) - numbers(h["new"])
        key = "+".join(h["ids"]) or "?"
        for tok, n in sorted(add.items()):
            why = None
            if tok in old_nums:
                why = "rc10"
            elif tok in allowed_art:
                why = "artifact:" + allowed_art[tok]
            elif tok in der:
                why = "derived: " + der[tok]
            else:
                for i in h["ids"]:
                    if tok in LITERALS.get(i, {}):
                        why = f"literal[{i}]: " + LITERALS[i][tok]
                        break
            rep[key]["added"].append((tok, n, why))
            if why is None:
                fails.append(f"number '{tok}' (+{n}) added in hunk {key} (rc11 l.{h['rc11'][0]}) is not justified")
        for tok, n in sorted(rem.items()):
            rep[key]["removed"].append((tok, n))
    # 3 headline values
    flat = " ".join(new.split())
    for k, v in headline(reg, chk, f4, f3, itt).items():
        if " ".join(v.split()) not in flat:
            fails.append(f"headline: {k} — expected text {v!r} (from the artifact) not found in rc11")
    # the census deviation is declared twice: in §4 and in Appendix A (Codex 1 asks for both)
    dev = " ".join(headline(reg, chk, f4, f3, itt)["census deviation"].split())
    sec4 = " ".join(new[new.find("\n## 4. Results"):new.find("\n### 4.0.1 ")].split())
    appa = " ".join(new[new.find("\n## Appendix A"):new.find("\n## Appendix B")].split())
    for nome, parte in (("§4", sec4), ("Appendix A", appa)):
        if dev not in parte:
            fails.append(f"census: the deviation is not declared in {nome}")
    # 4 claims
    fails += claims(new)
    # 5 headings
    h8, h9 = headings(old), headings(new)
    expected = [HEADINGS.get(h, (h, None))[0] for h in h8]
    if expected != h9:
        for x, y in zip(expected + [None] * 9, h9 + [None] * 9):
            if x != y:
                fails.append(f"heading: expected {x!r}, found {y!r}")
                break
    # 6 citations and footnotes
    for name, t in (("rc10", old), ("rc11", new)):
        body, refs = body_and_refs(t)
        used = set(re.findall(r"@([A-Za-z0-9_]+)", " ".join(CITE.findall(body))))
        listed = set(re.findall(r"`\[@([A-Za-z0-9_]+)\]`", refs))
        if used - listed:
            fails.append(f"citation ({name}): used but not listed: {sorted(used - listed)}")
        fm = set(re.findall(r"\[\^([^\]]+)\](?!:)", t))
        fd = set(re.findall(r"^\[\^([^\]]+)\]:", t, re.M))
        if fm - fd:
            fails.append(f"footnote ({name}): markers without definition {sorted(fm - fd)}")
    cn = collections.Counter(re.findall(r"@([A-Za-z0-9_]+)", " ".join(CITE.findall(body_and_refs(new)[0]))))
    co = collections.Counter(re.findall(r"@([A-Za-z0-9_]+)", " ".join(CITE.findall(body_and_refs(old)[0]))))
    if cn != co:
        fails.append(f"citation: occurrences changed: +{dict(cn - co)} -{dict(co - cn)}")
    if collections.Counter(DOI.findall(old)) != collections.Counter(DOI.findall(new)):
        fails.append("doi: DOI multiset changed")
    # 7 forbidden additions
    for pat in FORBIDDEN:
        if len(re.findall(pat, new)) > len(re.findall(pat, old)):
            fails.append(f"forbidden: pattern {pat!r} added")
    # 8 SHAM-JANELA
    so, eo = sham_spans(old)
    sn, en = sham_spans(new)
    fails += eo + en
    if len(sn) != EXPECTED_SHAM or len(so) != EXPECTED_SHAM:
        fails.append(f"sham: {len(sn)} blocks in rc11 and {len(so)} in rc10, expected {EXPECTED_SHAM}")
    for i, (x, y) in enumerate(zip(so, sn), 1):
        if x != y:
            fails.append(f"sham: block {i} ({y.strip()[:50]!r}…) is not byte-identical to rc10")
    # 9 no REANALISE comment marker
    if R_ANY.search(new):
        fails.append("reanalise: a REANALISE marker is present in rc11")
    # 10 quotes
    def nq(x):
        return " ".join(x.replace("**", "").split())
    fontes = nq(old) + " " + " ".join(nq(p.read_text()) for p in QUOTE_SOURCES)
    qo, qn = collections.Counter(QUOTE.findall(old)), collections.Counter(QUOTE.findall(new))
    for q in (qn - qo):
        if nq(q[2:-2]) not in fontes:
            fails.append(f"quote: {q[:70]!r} is not verbatim in rc10 or a declared source")
    for q in (qo - qn):
        fails.append(f"quote removed: {q[:70]!r}")
    # 11 code spans
    cos, cns = collections.Counter(CODE.findall(old)), collections.Counter(CODE.findall(new))
    roots = [P2, SPRINT, P2 / "out", REPO, LASTRO, SPRINT / "B-rc10", HERE, P2 / "measurement",
             SPRINT / "figures", REG]
    idsrc = "".join(p.read_text() for p in (ART["ITT-REGISTRADO-v3"], ART["checks-rc10"], ART["ITT-2026-09-21"],
                                            SCRIPT, P2 / "pilot_replay.py", P2 / "PREREG-DRAFT.md"))
    for span in (cns - cos):
        s = span.strip()
        if re.search(r"\.(?:py|json|md|svg|png|ndjson|jsonl|sh|tgz|txt|ts)\b|/$|\.\*$|\{", s) and " " not in s:
            pats = [s]
            m = re.search(r"\{([^}]+)\}", s)
            if m:
                pats = [s[:m.start()] + x + s[m.end():] for x in m.group(1).split(",")]
            for pat in pats:
                pat = pat.replace("…", "*")
                if not any(glob.glob(str(r / pat)) for r in roots):
                    fails.append(f"code span: `{span}` names no file on disk")
        elif re.fullmatch(r"[a-z][a-z0-9]*(?:_[a-z0-9]+)+", s):
            if s not in idsrc:
                fails.append(f"code span: identifier `{span}` occurs in none of the named sources")
    # 12 bold balance
    noncode = re.sub(r"```.*?```", "", new, flags=re.S)
    for k, para in enumerate(re.split(r"\n\s*\n", noncode)):
        if para.count("**") % 2:
            fails.append(f"bold: odd number of ** in paragraph {k}: {para.strip()[:60]!r}")
    # 13 script integrity
    fails += script_integrity(**(integ or load_integrity_inputs()))
    if verbose:
        print(f"hunks: {len(hs)}, all with an ID: {all(h['ids'] for h in hs)}")
        na = sum(len(v['added']) for v in rep.values())
        cls = collections.Counter((t[2] or "UNJUSTIFIED").split(":")[0] for v in rep.values() for t in v["added"])
        print(f"numeric tokens added across hunks: {na}; by class: {dict(cls)}")
        print(f"headings: {len(h9)}; renamed: {sum(1 for x, y in zip(h8, h9) if x != y)} (allowed {len(HEADINGS)})")
        print(f"SHAM-JANELA blocks: {len(sn)}, byte-identical to rc10: {sum(1 for x, y in zip(so, sn) if x == y)}")
        print(f"quotes added: {sum((qn - qo).values())}; code spans added: {sum((cns - cos).values())}")
    if report:
        for key, v in rep.items():
            print(f"\n[{key}]")
            for tok, n, why in v["added"]:
                print(f"  + {tok} x{n}  <- {why}")
            if v["removed"]:
                print("  - " + ", ".join(f"{t} x{n}" for t, n in v["removed"]))
    return fails


def main():
    old, new = OLD.read_text(encoding="utf-8"), NEW.read_text(encoding="utf-8")
    if "--report" in sys.argv:
        f = check(old, new, verbose=True, report=True)
        print("\n" + ("\n".join("FAIL " + x for x in f) or "no failures"))
        return 0
    if "--self-test" in sys.argv:
        integ = load_integrity_inputs()
        mut_v3 = copy.deepcopy(integ["v3_new"])
        mut_v3["pernas"]["registrado"]["hipoteses"]["H1"]["p_rerand"] = 0.3295
        mut_stale_script = integ["script_bytes"].replace(b"THE SIX SWITCHES", b"THE FOUR SWITCHES")
        mutations = [
            ("word changed inside a SHAM-JANELA block", new.replace("**Our error, stated.**", "**Our error.**", 1)),
            ("REANALISE marker inserted", new.replace("`p = 0.4006`", "<!-- REANALISE -->`p = 0.4006`<!-- /REANALISE -->", 1)),
            ("stratum repeats/hour changed", new.replace("+0.01867", "+0.01876")),
            ("stratum opportunities/hour changed", new.replace("+0.43543", "+0.43534")),
            ("H2 percentile bound changed", new.replace("+0.661]", "+0.616]")),
            ("census remaining count changed", new.replace("800 of the 5 556", "800 of the 5 565")),
            ("census deviation paragraph removed", new.replace(
                "This departs from the deposited sampling\nplan; the six-switch reanalysis does not restore the census.", "", 1)),
            ("span floor removed", new.replace("`max((max(ts) − min(ts))/3600, 1/60)` hours", "`max(ts) − min(ts)` hours", 1)),
            ("script sha prefix changed", new.replace("Script sha256 `0aa9202b…`", "Script sha256 `0aa9202c…`", 1)),
            ("dose lock: negation dropped", new.replace(
                "establishes that the rejection was not robust to the registered rule, not that the dose\nhad no effect",
                "establishes that the rejection was not robust to the registered rule, and that the dose\nhad no effect", 1)),
            ("dose lock: 'not of the dose' reintroduced", new.replace(
                "had no effect (§4.3).", "had no effect (§4.3). It was a property of how the denominator was computed and not of the dose.", 1)),
            ("dose lock: 'no effect of the dose' added", new.replace(
                "and does not test the\ndose (§1).", "and shows no effect of the\ndose (§1).", 1)),
            ("dose lock: 'was the denominator and not the dose'", new.replace(
                "that rejection went with the denominator:", "that rejection was the denominator and not the dose:", 1)),
            ("stale: 'no registered verdict differs' back", new.replace(
                "a sensitivity (§4). Under the deposited reading,", "a sensitivity (§4); no registered verdict differs between them. Under the deposited reading,", 1)),
            ("stale: 'report no cost, latency or energy' back", new.replace(
                "*did*. We report action-level", "*did*, and report no cost, latency or energy. We report action-level", 1)),
            ("stale: manifest 'every artifact in this table'", new.replace(
                "SHA-256 hashes of the 50 artifacts currently covered, for loss detection",
                "sha256 of every artifact in this table, for loss detection", 1)),
            ("stale: 'is the primary and is what' back", new.replace(
                "That is the analysis reported here (§4.1–4.3)",
                "It is the primary and is what §4.1–4.3 report; without coverage exclusion is the primary and is what they report", 1)),
            ("stale: 'The unexecuted abort' back", new.replace(
                "The absence of a\ncontemporaneous execution record for the safety abort is declared in Appendix A.",
                "The unexecuted abort is declared in Appendix A.", 1)),
            ("stale: §7 'not attributed as the registration requires' back", new.replace(
                "from rc10 every session is counted in the epoch\nof its start",
                "the sessions that span more than one epoch are not attributed as the registration requires, and from rc10 every session is counted in the epoch\nof its start", 1)),
            ("H1 rejects without 'deposited'", new.replace(
                "`H1` does not reject in the registered analysis under either reading",
                "`H1` rejects in the registered analysis under either reading", 1)),
            ("H1 rejects in the registered analysis under the deposited reading", new.replace(
                "In the registered\nanalysis H1 does not reject under either reading:",
                "In the registered\nanalysis H1 rejects under the deposited reading:", 1)),
            ("H1a presented as rejected", new.replace("and it is not rejected. Sources:", "and it is rejected. Sources:", 1)),
            ("stopping condition 'was met' unqualified", new.replace(
                "names was met under the planning definition, and the arm was not closed.",
                "names was met, and the arm was not closed.", 1)),
            ("1 195 called adjudicated", new.replace("All 1 195 were submitted to the", "All 1 195 were adjudicated by the", 1)),
            ("heading renamed", new.replace("### 4.3 H1: the interval", "### 4.3 H1 (rc11): the interval", 1)),
            ("quote fabricated", new.replace("LOCKED 2026-07-30: census, API-only panel", "LOCKED 2026-07-30: sample, API-only panel", 1)),
            ("code span names a missing file", new.replace("`_sprint-2026-10-04/APPLY-B-rc11.md`", "`_sprint-2026-10-04/APPLY-B-rc12.md`", 1)),
            ("IP address added", new.replace("Every\n> number below is measured", "Every\n> number below (10.1.2.3) is measured", 1)),
            ("citation removed", new.replace("[@cameron2008bootstrap; @webb2014reworking] motivates", "motivates", 1)),
            ("bold left unbalanced", new.replace("locked a census.** PREREG §3", "locked a census. PREREG §3", 1)),
            ("unmapped hunk with a new number", new.replace("**Benchmarks compare systems on fixed tasks.**",
                                                            "We ran 4217 extra checks.\n\n**Benchmarks compare systems on fixed tasks.**", 1)),
            ("headline interval changed", new.replace("[−0.0464; +0.0110]", "[−0.0464; +0.0101]")),
        ]
        PELA_CLAIM = {n for n, _ in mutations if n.startswith(("dose lock", "stale:", "H1 rejects", "H1a presented",
                                                               "stopping condition", "1 195"))}
        ok = True
        for name, mutated in mutations:
            assert mutated != new, f"mutation did not apply: {name}"
            f = claims(mutated) if name in PELA_CLAIM else check(old, mutated, verbose=False, integ=integ)
            # a catch by "hunk has no ID" alone does not count: it fires for any edit
            f = [x for x in f if "has no ID" not in x]
            via = "claim check" if name in PELA_CLAIM else "full check, content checks only"
            print(f"mutation [{name}] ({via}): {'CAUGHT' if f else 'MISSED'}" + (f" -> {f[0][:140]}" if f else ""))
            ok &= bool(f)
        mut_v3_prov = copy.deepcopy(integ["v3_new"])
        mut_v3_prov["proveniencia"]["script"]["sha256"] = hashlib.sha256(mut_stale_script).hexdigest()
        for name, kw, esperado in (
                ("regenerated v3 differs in a number", dict(integ, v3_new=mut_v3), "differs from rc10's v3"),
                ("stale string back in the script (copy and provenance consistent)",
                 dict(integ, script_bytes=mut_stale_script, frozen_bytes=mut_stale_script, v3_new=mut_v3_prov),
                 "stale string still present"),
                ("frozen copy differs from the script", dict(integ, frozen_bytes=integ["frozen_bytes"] + b"\n"),
                 "frozen v3 copy differs"),
                ("provenance records another script", dict(integ, v3_new=dict(integ["v3_new"], proveniencia=dict(
                    integ["v3_new"]["proveniencia"], script=dict(caminho="x", sha256="0" * 64)))),
                 "does not record the running script"),
                ("kept rc10 v3 bytes altered", dict(integ, kept_v3_bytes=integ["kept_v3_bytes"] + b" "),
                 "kept rc10 v3 bytes")):
            f = [x for x in script_integrity(**kw) if esperado in x]
            print(f"mutation [{name}] (script integrity): {'CAUGHT' if f else 'MISSED'}" + (f" -> {f[0][:140]}" if f else ""))
            ok &= bool(f)
        base = check(old, new, verbose=False, integ=integ)
        print(f"unmutated rc11: {'PASS' if not base else 'FAIL'}" + (f" -> {base}" if base else ""))
        return 0 if ok and not base else 1
    fails = check(old, new)
    for f in fails:
        print("FAIL", f)
    print("PARITY: PASS" if not fails else f"PARITY: FAIL ({len(fails)})")
    return 0 if not fails else 1


if __name__ == "__main__":
    sys.exit(main())
